# Dependabot config file.

# Copyright 2023 Qi Tianshi. All rights reserved.


version: 2

updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "qitianshi"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "qitianshi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "qitianshi"
