# Dependabot config file.

version: 2

updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "qitianshi"
    reviewers:
      - "qitianshi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "qitianshi"
    reviewers:
      - "qitianshi"
