# Dependabot config file.

version: 2

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "qitianshi"
    reviewers:
      - "qitianshi"
