# Dependabot config file.

# Copyright 2024 Qi Tianshi. All rights reserved.


version: 2

updates:

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "qitianshi"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "qitianshi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "qitianshi"
