# Jekyll configuration file

# Copyright 2023 Qi Tianshi. All rights reserved.


# --------- Jekyll ----------

url: "https://qitianshi.github.io"
baseurl: "/"
title: "tian"
lang: "en-US"
source: "./src"
exclude:
  - "README.md"
  - "node_modules"
sass:
  sourcemap: development
plugins:
  - jekyll-autoprefixer


# --------- Plugins ---------

# For jekyll-autoprefixer
autoprefixer:
  only_production: true
  browsers:
    - last 2 versions
