# Jekyll configuration file

# Copyright 2024 Qi Tianshi. All rights reserved.


# --------- Jekyll ----------

url: "https://qitianshi.com"
prod_url: "https://qitianshi.com"
baseurl: "/"
title: "tian"
lang: "en-US"
source: "./src"
exclude:
  - "README.md"
  - "node_modules"
sass:
  sourcemap: development
  style: compressed
plugins:
  - jekyll-autoprefixer
  - jekyll-minifier


# --------- Plugins ---------

# For jekyll-autoprefixer
autoprefixer:
  only_production: true
  browsers:
    - last 2 versions

# For jekyll-minifier
jekyll-minifier:
  compress_css: false           # Handled by Jekyll natively.
  compress_javascript: false    # Handled by webpack.
  remove_intertag_spaces: true
